 ## 과제 3

#### L=[1, 2, 3, 4, 5]일 때 다음 각 문장을 수행한 후의 결과를 보고 납득할 만한 이유를 설명하시오.
  - 1)
     - L[1:3] = [100]
     - print(L)
  -  2)
     - L[1:3] = [(100)]
     - print(L)
  -  3)
     - L[1:3] = 100
     - print(L)
  -  4)
     - L[1:3] = (100)
     - print(L)
  -  5)
     - L[1:3] = (100, 101, 102)
     - print(L)
  -  6)
     - L[1:3] = [100, 101, 102]
     - print(L)
  -  7)
     - L[1:3] = [(100, 101, 102)]
     - print(L)
  -  8)
     - L[1:3] = [[100, 101, 102]]
     - print(L)

In [21]:
L = [1, 2, 3, 4, 5]
L[1:3] = [100]
print(L)

[1, 100, 4, 5]


 L[1:3], 즉 L[1] 과 L[2]를 합쳐서 [100]으로 바꿔버리는 것이므로 2와 3이 없어지고 그 자리에 100이 들어가게 된다.

In [80]:
L = [1, 2, 3, 4, 5]
L[1:3] = [(100)]
print(L)

[1, 100, 4, 5]


 L[1:3], 즉 L[1] 과 L[2]를 합쳐서 [(100)]으로 바꿔버리는 것이므로 2와 3이 없어지고 그 자리에 100이 들어가게 된다.

In [87]:
L = [1, 2, 3, 4, 5]
L[1:3] = 100
print(L)

TypeError: can only assign an iterable

 iterable 타입으로 L[1:3]에 매칭해 넣으려면 100,으로 바꾸면 된다.

In [89]:
L = [1, 2, 3, 4, 5]
L[1:3] = (100)
print(L)

TypeError: can only assign an iterable

 iterable 타입으로 L[1:3]에 매칭해 넣으려면 (100,)으로 바꾸면 된다.

In [28]:
L = [1, 2, 3, 4, 5]
L[1:3] = (100, 101, 102)
print(L)

[1, 100, 101, 102, 4, 5]


  L[1:3], 즉 L[1] 과 L[2]를 합쳐서 (100, 101, 102)으로 바꿔버리는 것이므로 2와 3이 없어지고 그 자리에 100, 101, 102 가 들어가게 된다.

In [35]:
L = [1, 2, 3, 4, 5]
L[1:3] = [100, 101, 102]
print(L)

[1, 100, 101, 102, 4, 5]


 L[1:3], 즉 L[1] 과 L[2]를 합쳐서 [100, 101, 102] 으로 바꿔버리는 것이므로 2와 3이 없어지고 그 자리에 100, 101, 102 가 들어가게 된다.

In [36]:
L = [1, 2, 3, 4, 5]
L[1:3] = [(100, 101, 102)]
print(L)

[1, (100, 101, 102), 4, 5]


  L[1:3], 즉 L[1] 과 L[2]를 합쳐서 [(100, 101, 102)] 으로 바꿔버리는 것이므로 2와 3이 없어지고 그 자리에 (100, 101, 102) 가 들어가게 된다.

In [37]:
L = [1, 2, 3, 4, 5]
L[1:3] = [[100, 101, 102]]
print(L)

[1, [100, 101, 102], 4, 5]


 L[1:3], 즉 L[1] 과 L[2]를 합쳐서 [[100, 101, 102]] 으로 바꿔버리는 것이므로 2와 3이 없어지고 그 자리에 [100, 101, 102] 가 들어가게 된다.

 #### 문자열 S = 'Hello World and Python'에 대해 다음 요구사항에 대한 Python 코드를 제시하시오.
    1) 단어의 순서가 역순으로 되어진 문자열 ('Python and World Hello')을 만들고
    2) 1)의 결과 문자열에 대해 메소드 split과 join을 이용하여 공백을 모두 없엔 문자열 'PythonandWorldHello'을 만드시오.

In [52]:
S = 'Hello World and Python'
SQ = S[16:22]+' '+S[12:15]+' '+S[6:11]+' '+S[0:5]
TQ = SQ.split()
FQ = ''.join(TQ)
print(FQ)

PythonandWorldHello


먼저 슬라이싱을 이용해 단어의 순서가 역순이 되도록 붙인 후, split()을 이용해 공백을 없애고 마지막으로 join으로 붙였다.

 #### 다음 코드를 보고 물음에 답하시오.
      -  a = [1, 2, 3]
      -  b = a * 3
      -  c = [a] * 3
      -  print(b)
      -  print(c)

 #### 1) 위 코드를 수행한 이후 다음 코드를 수행한 후 b와 c의 내용을 확인하시오.
      -  a[0]=0

In [53]:
a = [1, 2, 3]
b = a * 3
c = [a] * 3
print(b)
print(c)

[1, 2, 3, 1, 2, 3, 1, 2, 3]
[[1, 2, 3], [1, 2, 3], [1, 2, 3]]


In [55]:
a[0] = 0
print(b)
print(c)

[1, 2, 3, 1, 2, 3, 1, 2, 3]
[[0, 2, 3], [0, 2, 3], [0, 2, 3]]


 a[0] = 0 으로 a리스트의 첫번째 원소를 0으로 바꾸어주니 a를 사용하는 b,c 도 같이 변했다. 이는 a의 바뀐 값을 가져갔다는 것이다.

#### 2) b와 c 객체의 차이는 무엇인가?

 b는 리스트인 a를 그대로 3배 불린 것이고, c는 리스트인 a를 한번 더 리스트 안에 넣어서 리스트가 리스트를 포함하고 있게 되었다.

 #### 다음 문자열을 ':'을 기준으로 분리하여 리스트로 만들고 각 문자열의 좌우 공백을 제거하시오 (즉, 문자열 S에서 l을 만들어라)
    s = '  first star   :   second star   :    third star ' 
    l = ['first star', 'second star', 'third star']

 #### 1) for ~ in 문을 이용한 코드를 작성하시오.

In [58]:
s = '  first star   :   second star   :    third star '
s1 = s.split(':')
L = []
for k in range(3):
    L.append(s1[k].strip())
print(L)

['first star', 'second star', 'third star']


 s를 : 를 기준으로 나눈 리스트를 만들고, for ~ in 문을 이용해 append로 빈 리스트 L에 각 요소의 strip()을 적용해 공백을 없앤 후 더하게 된다.

 #### 2) 리스트 내포(list comprehension)를 이용한 코드를 작성하시오.

In [60]:
s = '  first star   :   second star   :    third star '
s1 = s.split(':')
L = [s1[k].strip() for k in range(3)]
print(L)

['first star', 'second star', 'third star']


 리스트 내포 리터럴 방식을 활용해서 1번을 2번처럼 변경할 수 있다.

 #### 다음과 같이 0보다 큰 정수 리스트 변수 list를 인자로 받는 함수 addall(list)와 addallodd(list)를 for ~ in 리터널과 리스트 내포 방식으로 각각 제시하시오.

 ##### 1) addall(list) 함수 (리스트 내의 모든 정수를 더하는 함수로서 해답으로는 for ~ in 리터럴과 리스트 내포 방식으로 각각 제시하시오.)

In [25]:
def addall(lista):
    L = []
    for k in lista:
        if k>0:
            if k==int(k):
                L.append(k)
    return sum(L)
print(addall([-5,2,3,4,0.5]))

9


 리스트를 받아서 for~in 리터럴을 이용해 내부의 모든 정수를 더하는 함수이다.

In [24]:
def addall(lista):
    L = [k for k in lista if k>0 if k==int(k)]
    return sum(L)
print(addall([-5,2,3,4,0.5]))

9


 리스트를 받아서 리스트 내포 리터럴 방식으로 리스트 내의 정수만을 가져와 새로운 리스트를 만든 후, 새로운 리스트 내부의 모든 값들을 더해서 반환한다.

 ##### 2) addallodd(list) 함수 (리스트내의 모든 홀수를 더하는 함수로서 해답으로는 for ~ in 리터럴과 리스트 내포 방식으로 각각 제시하시오.)

In [22]:
def addallodd(lista):
    L = []
    for k in lista:
        if k>0:
            if k==int(k):
                if k%2:
                    L.append(k)
    return sum(L)
print(addallodd([-2,1,2,3,4,0.5,11]))

15


 리스트를 받아서 for~in 리터럴 방식으로 홀수만 가져와 새로운 리스트를 만든 후, 새로운 리스트 내부의 모든 값을 더하는 함수이다.

In [26]:
def addallodd(lista):
    L = [k for k in lista if k>0 if k==int(k) if k%2]
    return sum(L)
print(addallodd([-2,1,2,3,4,0.5,11]))

15


리스트를 받아서 리스트 내포 리터럴 방식으로 리스트 내의 홀수만을 가져와 새로운 리스트를 만든 후, 새로운 리스트 내부의 모든 값들을 더해서 반환한다.

 #### 다음 코드를 보고 물음에 답하시오.

- L1 = [1, 2, 3]
- L2 = [4, 5, 6]
- d = {'low':L1, 'high':L2}
- e = d
- f = d.copy()
- print(d)
- print(e)
- print(f)
- print()
- d['low'] = [10, 20, 30]
- d['high'][1] = 500
- print(d)
- print(e)
- print(f)

In [29]:
L1 = [1, 2, 3]
L2 = [4, 5, 6]
d = {'low':L1, 'high':L2}
e = d
f = d.copy()
print(d)
print(e)
print(f)
print()
d['low'] = [10, 20, 30]
d['high'][1] = 500
print(d)
print(e)
print(f)

{'low': [1, 2, 3], 'high': [4, 5, 6]}
{'low': [1, 2, 3], 'high': [4, 5, 6]}
{'low': [1, 2, 3], 'high': [4, 5, 6]}

{'low': [10, 20, 30], 'high': [4, 500, 6]}
{'low': [10, 20, 30], 'high': [4, 500, 6]}
{'low': [1, 2, 3], 'high': [4, 500, 6]}


 ##### 1) 위 코드의 수행 결과 d와 e는 항상 같은 결과를 출력한다. 그 이유는 무엇인가?

 e = d 때문에 e와 d가 동일한 객체를 참조하게 되기 때문에 일어나는 현상이다.

  ##### 2) 위 코드의 수행 결과 마지막 f의 내용은 다음과 같다. 이 때 'high' 키의 값 내용 중 500이 출력된 이유와 'low' 키의 값 내용 중 [1, 2, 3]이 출력된 이유를 설명하시오 
  - {'high': [4, 500, 6], 'low': [1, 2, 3]}

 shallow copy, 즉 얕은 복사가 이루어졌기 때문에 복사된 f리스트는 별도의 객체이다. 그러므로 low키의 값 내용은 바뀌기 전 값인  [1,2,3]이 된다.

 #### 사전 d = {'one':1, 'two':2, 'three':3, 'four':4, 'five':5}가 주어졌을 때 다음 요구사항에 맞는 코드를 제시하시오

 ##### 1) 키의 알파벳 오름차순 순서대로 튜플 (키, 값)을 차례대로 출력하시오.

In [73]:
d = {'one':1, 'two':2, 'three':3, 'four':4, 'five':5}
L = [] 
key = d.keys()
for k in key:
    L.append(k)
L.sort()
for k in L:
    print((k, d[k]))

('five', 5)
('four', 4)
('one', 1)
('three', 3)
('two', 2)


 keys() 메소드를 호출해 나온 key값으로 구성된 리스트를 sort를 이용해 정렬하면 key값에 의한 정렬을 할 수 있다.

##### 2) 키의 알파벳 내림차순 순서대로 튜플 (키, 값)을 차례대로 출력하시오.

In [102]:
d = {'one':1, 'two':2, 'three':3, 'four':4, 'five':5}
L = [] 
key = d.keys()
for k in key:
    L.append(k)
L.sort(reverse = True)
for k in L:
    print((k, d[k]))

('two', 2)
('three', 3)
('one', 1)
('four', 4)
('five', 5)


 keys() 메소드를 호출해 나온 key값으로 구성된 리스트를 sort를 이용해 정렬하면 key값에 의한 정렬을 할 수 있다. 이 때, sort(reverse = True)를 활용해 역순으로 정렬할 수 있다.

 ##### 3) 값의 오름차순 순서대로 튜플 (키, 값)을 차례대로 출력하시오.

In [104]:
d = {'one':1, 'three':3, 'ten':10, 'four':4, 'five':5}
L = [] 
V = []
value = d.values()
for k in value:
    L.append(k)
L.sort()
for k, x in d.items():
    for t in L:
        if x == t:
            V.insert(L.index(t),(k,x))
print(V)
#print(L)

[('one', 1), ('three', 3), ('four', 4), ('five', 5), ('ten', 10)]


 values() 메소드를 호출해 나온 value값으로 구성된 리스트를 sort를 이용해 정렬하고, 이를 이중 for~in문 안에서 items() 메소드로 호출한 key값과 value값 두개의 리플에서 value값이 정렬된 value 리스트의 값과 일치할 시 그 값에 맞는 인덱스에 넣어주는 방식으로 새로운 리스트 V를 만들어 그 안에 저장한다.

 ##### 4) 값의 내림차순 순서대로 튜플 (키, 값)을 차례대로 출력하시오.

In [103]:
d = {'one':1, 'three':3, 'ten':10, 'four':4, 'five':5}
L = [] 
V = []
value = d.values()
for k in value:
    L.append(k)
L.sort(reverse = True)
for k, x in d.items():
    for t in L:
        if x == t:
            V.insert(L.index(t),(k,x))
print(V)
#print(L)

[('ten', 10), ('five', 5), ('one', 1), ('four', 4), ('three', 3)]


 values() 메소드를 호출해 나온 value값으로 구성된 리스트를 sort를 이용해 정렬하고, 이를 이중 for~in문 안에서 items() 메소드로 호출한 key값과 value값 두개의 리플에서 value값이 정렬된 value 리스트의 값과 일치할 시 그 값에 맞는 인덱스에 넣어주는 방식으로 새로운 리스트 V를 만들어 그 안에 저장한다. 이 때, sort(reverse = True)를 활용해 역순으로 정렬할 수 있다.

 #### [ACM-ICPC 문제 1152번]
 - 단어의 개수

In [107]:
s = input()
s1 = s.split()
print(len(s1))

The Curious-Case of Benjamin Button
5


 문장을 하나 입력받고 이를 split()을 이용해 공백 문자를 기준으로 나눈 리스트의 크기를 확인하면 된다.

 ![이미지](https://github.com/fun5733/-Assignment_2015136069/blob/master/PPP/5.png?raw=true)

 #### [Incremental Project] 이전 Assignment 2의 마지막 문제는 웹 URL로 지정된 웹페이지를 문자열로 가져와 모든 HTML 태그 및 CSS와 Javascript를 제외한 순수 텍스트를 얻어내고 그 안에 존재하는 단어를 추출하고 단어들의 총 개수를 출력하는 프로그램을 작성하는 것이었다. 이번에는 그 마지막 숙제를 그대로 확장하여 웹 URL로 지정된 웹페이지 내 순수 텍스트 안에 존재하는 각 단어들에 대해 다음 요구사항 대로 출력하는 프로그램을 작성하시오.

##### 요구사항 1. 순수 텍스트 안에 존재하는 단어들에 대해 string 모듈을 활용하여 모든 punctuation (구두문자)를 완벽히 제거하시오.
 - 예: ['world!', ':', '+hello+', '~python$$$', '=', 'world'] ---> ['world', 'hello', 'python', 'world']
 - 모든 punctuation을 확인하는 방법은 아래와 같다.
   - import string
   - print(string.punctuation)

In [43]:
import string
i = 0
P = list(range(len(string.punctuation)))
L =  ['world!', ':', '+hello+', '~python$$$', '=', 'world']
for k in string.punctuation:
    P[i] = k
    i = i+1
V = []
for k in L:
    for x in P:
        if x in k:
            num = k.count(x)
            for t in range(num):
                idx = k.index(x)
                k = k[:idx] + k[idx+1:]
    V.append(k)
print(V)

['world', '', 'hello', 'python', '', 'world']


 일단 모든 punctuation을 리스트 P안에 한 개씩 따로 저장한 뒤, 리스트 L 내의 각각의 문자열 값이 punctuation을 하나라도 가지면 그 인덱스의 값을 제외한 나머지만을 다시 더한 문자열을 새로 생성 후 새로운 리스트에 append로 추가한다. 

 ##### 요구사항 2. 만약 punctuation (구두문자)를 제거한 이후 공백으로 판명되는 단어들은 해당 단어 리스트에서 제거하시오.
  - 예: ['컴퓨터공학부!', '---?', '%지향~', '...'] ---> ['컴퓨터공학부', '지향']

In [48]:
import string
i = 0
P = list(range(len(string.punctuation)))
L = ['컴퓨터공학부!', '---?', '%지향~', '...',]
for k in string.punctuation:
    P[i] = k
    i = i+1
V = []
for k in L:
    for x in P:
        if x in k:
            num = k.count(x)
            for t in range(num):
                idx = k.index(x)
                k = k[:idx] + k[idx+1:]
    V.append(k)
for k in V:
    if len(k)==0:
        V.remove(k)
print(V)

['컴퓨터공학부', '지향']


 위에서 puntuation 제거하는 코드를 그대로 쓰되, 마지막에 공백으로 판명되는 단어, 즉 길이가 0인 문자열을 모두 remove로 제거했다.

 ##### 요구사항 3. 각 단어들의 출현빈도를 사전형태로 저장하여 출력하시오.
   - 예: ['world', 'hello', 'python', 'world', '컴퓨터공학부', '지향'] ---> {'world': 2, 'hello': 1, 'python': 1, '컴퓨터공학부': 1, '지향': 1}

In [6]:
import string
i = 0
P = list(range(len(string.punctuation)))
L = ['world', 'hello', 'python', 'world', '컴퓨터공학부', '지향']
for k in string.punctuation:
    P[i] = k
    i = i+1
V = []
M = {}
for k in L:
    for x in P:
        if x in k:
            num = k.count(x)
            for t in range(num):
                idx = k.index(x)
                k = k[:idx] + k[idx+1:]
    V.append(k)
for k in V:
    if len(k)==0:
        V.remove(k)
for k in V:
    M[k] = V.count(k)
print(V)
print(M)

['world', 'hello', 'python', 'world', '컴퓨터공학부', '지향']
{'world': 2, 'hello': 1, 'python': 1, '컴퓨터공학부': 1, '지향': 1}


 for in문을 통해 리스트 V 내부의 값을 확인하고 사전의 key값, 이 값이 리스트 내에 몇 개나 있는지 count로 세서 사전의 value값으로 저장한다.

 ##### 요구사항 4. 다음 3개의 사이트에 대한 결과를 출력하시오.
   - http://www.naver.com
   - http://www.daum.net
   - http://www.nytimes.com

In [8]:
from urllib import request 
 
url = 'http://www.naver.com'
f = request.urlopen(url)
source_bytes = f.read()
source = source_bytes.decode('utf-8')
re = source.split('<')
i = 0
st = ''
count = 0
s2 = list(range(len(re)))
s3 = list(range(len(re)))
for x in re[1:]:
    if '>' not in x:
        re.remove(x)
for x in re[1:]:
    s = x.split('>')
    s.reverse()
    s3[i] = s[0]
    i = i+1
for x in s3:
    st = st+str(x)
st1 = st.split()
for x in st1:
    count = count+1
#print(count)
#print(st1)

i = 0
P = list(range(len(string.punctuation)))
L = st1
for k in string.punctuation:
    P[i] = k
    i = i+1
V = []
M = {}
for k in L:
    for x in P:
        if x in k:
            num = k.count(x)
            for t in range(num):
                idx = k.index(x)
                k = k[:idx] + k[idx+1:]
    V.append(k)
for k in V:
    if len(k)==0:
        V.remove(k)
for k in V:
    M[k] = V.count(k)
#print(V)
print(M)

{'var': 19, 'nsc': 1, 'navertopv3': 1, 'documentdomain': 1, 'navercom': 1, 'jindoAll': 1, 'httpsspstaticnetpm2jscjindov171025js': 1, 'if': 4, 'windowconsole': 1, 'windowconsolewindowconsolelogfunction': 1, 'isLogin': 1, 'false': 4, 'function': 5, 'refreshLcsetc': 1, 'etc': 4, 'ifdocumentcookieindexOfnrefreshx1': 1, '1': 4, 'etcmrf1': 1, 'else': 1, 'etcpanbtyreturn': 1, 'lcsdorefreshLcs': 1, 'NAVER': 3, '뉴스스탠드': 2, '바로가기': 6, '주제별캐스트': 1, '타임스퀘어': 1, '쇼핑캐스트': 2, '로그인': 2, '네이버': 7, '네이버를': 1, '시작페이지로': 1, '쥬니어네이버': 1, '해피빈': 1, '검색': 2, '통합검색블로그카페': 1, '카페명': 1, '카페글지식iN뉴스사이트': 1, '카테고리': 1, '사이트영화웹문서사전': 1, '백과사전': 1, '영어사전': 1, '영영사전': 1, '국어사전': 1, '일본어사전': 1, '한자사전': 1, '용어사전책음악전문자료쇼핑지역동영상이미지내PC영화자동차게임건강인물긍정부정검색': 1, '자동완성': 12, '펼치기': 1, '한글': 1, '입력기': 1, '생각한대로': 1, '검색해': 1, '보세요': 2, 'Beta': 1, 'txttxt': 1, '시간대와': 1, '관심사에': 1, '맞춘': 1, '컨텍스트': 3, '도움말': 2, '보기': 21, 'ON선택됨': 1, 'OFF': 1, '동일한': 1, '시간대연령남녀별': 1, '사용자': 1, '그룹의관심사에': 1, '맞춰': 1, '자동완성을': 1, '제공합니다': 1, '자세히': 

In [71]:
from urllib import request 
 
url = 'http://www.daum.net'
f = request.urlopen(url)
source_bytes = f.read()
source = source_bytes.decode('utf-8')
re = source.split('<')
i = 0
st = ''
count = 0
s2 = list(range(len(re)))
s3 = list(range(len(re)))
for x in re[1:]:
    if '>' not in x:
        re.remove(x)
for x in re[1:]:
    s = x.split('>')
    s.reverse()
    s3[i] = s[0]
    i = i+1
for x in s3:
    st = st+str(x)
st1 = st.split()
for x in st1:
    count = count+1
#print(count)
#print(st1)

i = 0
P = list(range(len(string.punctuation)))
L = st1
for k in string.punctuation:
    P[i] = k
    i = i+1
V = []
M = {}
for k in L:
    for x in P:
        if x in k:
            num = k.count(x)
            for t in range(num):
                idx = k.index(x)
                k = k[:idx] + k[idx+1:]
    V.append(k)
for k in V:
    if len(k)==0:
        V.remove(k)
for k in V:
    M[k] = V.count(k)
#print(V)
print(M)

{'Daum': 1, 'charset': 1, 'utf8': 1, 'bodydivdldtddulollih1h2h3h4h5h6precodeformfieldsetlegendtextareapblockquotethtdinputselectbuttonmargin0padding0': 1, 'fieldsetimgborder0': 1, 'none': 5, 'dlulolmenuliliststylenone': 1, 'blockquote': 1, 'qquotes': 1, 'blockquotebefore': 1, 'blockquoteafterqbefore': 1, 'qaftercontentcontentnone': 1, 'inputselecttextareabuttonverticalalignmiddle': 1, 'inputmscleardisplaynone': 1, 'buttonborder0': 1, 'nonebackgroundcolortransparentcursorpointer': 1, 'bodybackgroundfffdirectionltrwebkittextsizeadjustnone': 1, 'bodythtdinputselecttextareabuttonfontsize13pxlineheight15fontfamilyAppleSDGothicNeoRegularMalgun': 1, 'Gothic맑은': 1, '고딕dotum돋움sansserifcolor222letterspacing1px': 1, 'osmac': 144, 'bodyosmac': 1, 'thosmac': 1, 'tdosmac': 1, 'inputosmac': 1, 'selectosmac': 1, 'textareaosmac': 1, 'buttonletterspacing0': 1, 'acolor222textdecorationnone': 1, 'ahovercolor118efftextdecorationunderline': 1, 'aactivebackgroundcolortransparent': 1, 'addresscaptioncitecoded

In [5]:
from urllib import request 
 
url = 'http://www.nytimes.com'
f = request.urlopen(url)
source_bytes = f.read()
source = source_bytes.decode('utf-8')
re = source.split('<')
i = 0
st = ''
count = 0
s2 = list(range(len(re)))
s3 = list(range(len(re)))
for x in re[1:]:
    if '>' not in x:
        re.remove(x)
for x in re[1:]:
    s = x.split('>')
    s.reverse()
    s3[i] = s[0]
    i = i+1
for x in s3:
    st = st+str(x)
st1 = st.split()
for x in st1:
    count = count+1
#print(count)
#print(st1)

i = 0
P = list(range(len(string.punctuation)))
L = st1
for k in string.punctuation:
    P[i] = k
    i = i+1
V = []
M = {}
for k in L:
    for x in P:
        if x in k:
            num = k.count(x)
            for t in range(num):
                idx = k.index(x)
                k = k[:idx] + k[idx+1:]
    V.append(k)
for k in V:
    if len(k)==0:
        V.remove(k)
for k in V:
    M[k] = V.count(k)
#print(V)
print(M)

NameError: name 'string' is not defined

 과제 2에서 작성한 코드와 합쳐서 각각의 사이트에 대한 결과를 출력했다.